### ISSUE TITLE
Cant Use .ELF?

### ISSUE THREAD

**Issue by OrtegaUS1** [wiiu-env/Aroma#18]
When i use them my console just freezes i want to use something like HBL2HBC

**Comment by mikurindotc** [comment]
You can't run .elfs on Aroma, I'm using Tiramisu for this.

**Comment by czerwinski76** [comment]
@OrtegaUS1Same thing for me on the latest build of Aroma. shutdown.rpx and sudokul.rpx works great but homebrew_launcher.rpx gives me black screen (freezed).

"For older homebrews: use tiramisu
Some older homebrew applications (typically those in ELF format ) cannot be launched from Aroma. It is then necessary to load [Tiramisu](https://wiidatabase-de.translate.goog/wii-u-downloads/hacks/tiramisu/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp) to use these. It must of course be on the SD card.

If you have set up coldboot: Hold "X" while starting the console
Otherwise: Hold "X" when launching the "Health & Safety Alerts" app
Choose " tiramisu " here. If you want to use aroma again, turn off the console and repeat the above process to select "aroma" again (or if it's set as default, just launching the console/"Health & Safety Alerts") is enough .

To open the Homebrew Launcher , launch Mii Maker . This only works under tiramisu ."
https://wiidatabase.de/wii-u-downloads/hacks/aroma/

"Aroma does not support the Homebrew Launcher
Launch apps from the Wii U menu using the homebrew_on_menu plugin."
https://wiiu.hacks.guide/#/aroma/finalizing-setup

Some homebrews have been ported to aroma in .wuhb format.
You can test Boot2vWii version here : https://gbatemp.net/attachments/boot2vwii-zip.343875/
https://gbatemp.net/threads/boot2vwii-precompiled.618963/

**Comment by OrtegaUS1** [comment]
ok i have it now Thanks!
